#!/bin/bash

run_location=$1
sim_dir=$2
min=$3
max=$4
nbeams=$5
num_openmp=$6
homedir=$(pwd)

echo "Running example "$min" to "$max" with mpi_procs="$nbeams" and openmp_threads="$num_openmp" per proc"
export OMP_NUM_THREADS=$num_openmp

for i in $(seq $min $max)
do
    cd $run_location$i$sim_dir
    chmod +x main
    mpirun -np $nbeams ./main>a.out &
    cd $homedir
done

wait
